### ISSUE TITLE
Move to System.loader.import loader

### ISSUE THREAD

**Issue by guybedford** [ModuleLoader/es-module-loader#455]
Currently we create a `System` global which is an instance of the loader.

`System` is now being specified as a generic object which will contain other system-level variables.

As a result, this implementation will conflict with new spec work in future. Luckily we create `System.global` so align with the current `System.global` spec, but other changes may cause irresolvable conflicts.

The proposal is to export `System.loader` as the current `System` instance, within the existing implementation. This way we don't have to take the risk of the full new spec upgrade (while it is still being finalised), but can just make this one breaking modification to align the global name.

In addition, it may also be worth not defining `System.loader` if it is already defined (native implementation), and instead work from `global.SystemLoaderPolyfill` in this case.

The above would hopefully set a suitable course for the transition into native modules.

**Comment by joeldenning** [comment]
This is a pretty big breaking change -- would SystemJS maintain backwards compatibility of `System.import`? If not, will this be a major version bump (to avoid breaking things for the users who are using `System.import`)? Also, would this be published as `latest` immediately, or would there be a beta/rc period?

**Comment by guybedford** [comment]
SystemJS isn't going to use the new spec for a long while yet due to stability requirements. Rather SystemJS will transition to using `SystemJS.import` (with a long deprecation phase of `System.import` at the same time) until the spec is deemed stable to move to this form. 

So the two projects will likely be out of sync this year. Hence why it would be great to start moving things along here without the burden of SystemJS's needs.

This ES Module Loader project doesn't need to worry about backwards compatibility, it just needs to track the spec. Releasing the spec-parity version when it's ready is the only priority to worry about here.

**Comment by probins** [comment]
if the spec is using `System.loader.import` rather than `System.import`, then current users (including me) are going to have to change their code at some point anyway. @guybedford do I understand correctly that you see `SystemJS.import` as a temporary thing until the spec is stable and defines `System.loader.import` (or whatever the spec does finally settle on)?

**Comment by guybedford** [comment]
@probins yes exactly, this makes the SystemJS change simply a namespacing change, instead of upgrading the entire API. We then allow the spec to settle before updating SystemJS to it, as it is still not stable, while SystemJS is.

**Comment by probins** [comment]
makes sense to me. Happy new year btw :-)

**Comment by guybedford** [comment]
Sure, and thanks for another year of your feedback :)

**Comment by joeldenning** [comment]
Why change from `System.import` to `SystemJS.import`, only to then change to `System.loader.import`, if there is nothing that yet conflicts with SystemJS' implementation of `System`? Isn't it harder for the user to change twice instead of once?

Would it make sense to wait until there's at least one conflicting addition to `System` before deciding to ask users to migrate twice? As you pointed out, the `System.global` spec doesn't conflict, and as far as I know there are no other conflicting uses of `System` that are even in stage 0.

**Comment by guybedford** [comment]
@joeldenning think of it more like treating SystemJS as a custom loader, to avoid mutating the global loader, at least until the spec is clear on how to handle this.

**Comment by guybedford** [comment]
This is running now on the 1.0 release.
