### ISSUE TITLE
Experimenting with SystemJS v0.20

### ISSUE THREAD

**Issue by blittle** [ModuleLoader/es-module-loader#523]
I am experimenting rewriting a [SystemJS plugin](https://github.com/CanopyTax/sofe) with the new SystemJS v0.20 API.

The documented API for creating plugins: https://github.com/systemjs/systemjs/blob/0.20/docs/creating-plugins.md does not work due to this code being disabled within `es-module-loader` https://github.com/ModuleLoader/es-module-loader/blob/next/core/loader-polyfill.js#L215 

I get an error at this line because `evaluate` was never defined: https://github.com/ModuleLoader/es-module-loader/blob/next/core/register-loader.js#L712

**Comment by blittle** [comment]
This might already be a known problem, I am dealing with an alpha release :) If not, I thought you should know.

**Comment by guybedford** [comment]
@blittle thanks for trying out the Alpha, feedback is really useful. I think this was fixed in https://github.com/ModuleLoader/es-module-loader/commit/8437da0fd67ea6f2b2feb552c59c633bc698c562 by just removing the `nsEvaluate` call entirely, will hopefully have a new release out in the next week or so.

**Comment by blittle** [comment]
@guybedford thanks! I'm super excited about the rewrite! I'll anxiously await the next release.
